channels:
- conda-forge
dependencies:
- python=3.11.5
- pip<=23.2.1
- pip:
  - mlflow==2.7.1
  - catboost==1.2.2
  - ipython==8.15.0
  - numpy==1.26.0
  - pandas==2.1.1
  - scipy==1.11.3
name: mlflow-env
